import { AppstoreOutlined, SettingOutlined } from "@ant-design/icons";
export const menuList = [
    {
        url:'/Home',
        key:'1',
        icon:<AppstoreOutlined />,
        children:undefined,
        label:'首页',
    },
    {
        url:'',
        key:'sub1',
        icon:<AppstoreOutlined />,
        children:[
            {
                url:'/Article',
                key:'2',
                icon:'',
                children:undefined,
                label:'文章列表',
                disabled:false
            },
            {
                url:'/Article/detail',
                key:'2-1',
                icon:'',
                children:undefined,
                label:'文章详情',
                disabled:true
            },
            {
                url:'/Project',
                key:'3',
                icon:'',
                children:undefined,
                label:'项目列表',
                disabled:false
            },
            {
                url:'/Message',
                key:'4',
                icon:'',
                children:undefined,
                label:'留言列表',
                disabled:false
            },
            {
                url:'/Tags',
                key:'5',
                icon:'',
                children:undefined,
                label:'标签列表',
                disabled:false
            },
        ],
        label:'基础管理',
    },
    {
        url:'',
        key:'sub2',
        icon:<SettingOutlined />,
        children:[
            {
                url:'/User',
                key:'6',
                icon:'',
                children:undefined,
                label:'用户管理',
                disabled:false
            },
            {
                url:'/Menu',
                key:'7',
                icon:'',
                children:undefined,
                label:'菜单管理',
                disabled:false
            },
        ],
        label:'系统管理',
    },
]